### PR TITLE
Update dependency Result to non-beta version 

### PR DESCRIPTION
**Pull request by danthorpe**
In this file: https://github.com/danthorpe/Money/blob/development/Money.podspec, it shows a dependency:
```
s.dependency 'Result', '0.6.0-beta.6'
```

The beta version number causes a CFBundleVersion error when uploading to iTunes, as per this Stackoverflow thread: http://stackoverflow.com/a/33375436/4769084

My interim solution was to manually update the info.plist file of the pod, however using a non-beta dependency would probably be better.

### CODE REVIEW

**Comment by hsoi** [comment]
No worries @danthorpe ! I'm taking @mrdavey 's same approach and just hacking the Info.plist of Result so I can build and submit (gotta get it submitted this morning).

But to have this properly sorted out will be good for post-release :+1: 

Thanx again!

**Comment by danthorpe** [comment]
@mrdavey @hsoi - okay, sounds good - being practical. I knew that `-beta6` was going to be a problem eventually... Also great that you're submitting apps with Money! (I've not actually got round to it myself yet!) :+1:

**Comment by danthorpe** [comment]
Push `1.4.2` to CocoaPods 😀

**Comment by hsoi** [comment]
@danthorpe thank you! Got it updated and things seem good.

Yup. Just submitted an app using Money [ScoreSense Scores To Go](https://itunes.apple.com/us/app/scoresense-scores-to-go-free/id964887531?mt=8), the 2.0 version will be using it. Helped me with some parsing and display stuff. :+1: 

Thanx for it!

**Pull request merged**
